server:
  port: 9201

############### consul config
---
spring:
  cloud:
    consul:
      host: 1.14.94.46    # 注册consul服务的主机
      port: 8500          # 注册consul服务的端口
      discovery:
        register-health-check: true # consul服务的健康检查 （不推荐关闭 默认为true）
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
